# Generated by Django 5.0.4 on 2024-07-06 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='autoS/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoS.names')),
            ],
        ),
    ]
