# Generated by Django 5.0.4 on 2024-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='names',
            name='recipieLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
