# Generated by Django 5.0.6 on 2024-07-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='kjapp/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='file',
        ),
    ]
