# Generated by Django 4.2.13 on 2024-09-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='diet_preference',
            field=models.CharField(choices=[('Vegetarian', 'Veg'), ('Non-Vegetarian', 'Non-Veg'), ('Vegan', 'Vegan')], max_length=15),
        ),
        migrations.AlterField(
            model_name='client_plan',
            name='status',
            field=models.CharField(choices=[('Created', 'Create'), ('Active', 'Activate'), ('Paused', 'Pause'), ('Suspended', 'Suspend'), ('Expired', 'Expire')], max_length=20),
        ),
    ]
