# Generated by Django 5.0.6 on 2024-07-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjapp', '0002_fileupload_remove_client_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kjapp.client'),
        ),
    ]
