# Generated by Django 5.0.6 on 2024-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjapp', '0004_alter_fileupload_client_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_plan',
            name='count_down',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
