# Generated by Django 5.0.6 on 2024-07-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjapp', '0005_client_plan_count_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
