# Generated by Django 5.0.6 on 2024-08-02 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjapp', '0006_address_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_plan',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
