# Generated by Django 5.0.6 on 2024-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kjapp', '0007_diet_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_plan',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
