name: django-pipeline


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      CI : true
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST : localhost
      DB_PORT : 5430


    services:
      postgres:
        image: postgres:16
        ports:
          - 5430:5432
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
    

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository manually
        run: |
           git clone https://github.com/ayuj9/kjpanel-django.git
           cd kjpanel-django


      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Build Docker image
        run: |
            docker build -t myapp:latest .
            docker save myapp:latest > myapp.tar    
            
            

      - name: Setting django server
        run : bash ./bashScripts/setup_django.sh &

      - name: Waiting for Server to come up
        run: |
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000/ > /dev/null; then
              echo "Server is up"
              break
            fi
            echo "Waiting ..."
            sleep 10
          done
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
            name: myapp-image
            path: myapp.tar

  test:
    runs-on: ubuntu-latest
    needs : build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: myapp-image    

      - name: Load Docker image
        run: |
            docker load -i myapp.tar
            docker run -d -p 8080:8080 myapp:latest
            sleep 20  # Wait for the server to initialize
        

      - name : check server
        run : curl http://localhost:8080/health  

      - name : test file
        run : source ./bashScripts/run_test.sh
