name: django-pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      DB_NAME: kjpanel
      DB_USER: postgres
      DB_PASSWORD: ghar12345
      DB_HOST: localhost
      DB_PORT: 5432
      RUN_TEST: Yes

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setting django server
        run: |
          python3 -m venv .venv1
          source .venv1/bin/activate
          pip install -r requirements.txt
          python -m pip install pytest
        # bash ./bashScripts/run_test.sh &
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db

      # - name: Waiting for Server to come up
      #   run: |
      #     for i in {1..30}; do
      #       if curl -s http://127.0.0.1:8000/ > /dev/null; then
      #         echo "Server is up"
      #         break
      #       fi
      #       echo "Waiting ..."
      #       sleep 10
      #     done

      - name: Run Test
        if: ${{env.RUN_TEST == 'Yes'}}
        env:
          DATABASE_URL: postgres://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/test_db
        run: |
          pytest
