name: django-pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      DB_NAME: kjpanel
      DB_USER: postgres
      DB_PASSWORD: ghar12345
      DB_HOST: localhost
      DB_PORT: 5432
      RUN_TEST: Yes

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: make install

      - name: Run test
        if: ${{ env.RUN_TEST == 'Yes' }}
        run: pytest .
