name: django-pipeline



   

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   DB_URL: postgres://username:password@localhost/dbname

    services:
      postgres:
        image: postgres:16

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: checkout actions
        uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}

      - name : Activate Virtual Enviornment
        run :  bash ./bashScripts/run_env.sh     

      - name: Install dependencies with bash
        run: bash ./bashScripts/install_dep.sh



      # - name: Collect static files
      #   env:
      #     DATABASE_URL: ${{ secrets.DB_URL }} # Set in GitHub Secrets
      #   run: |
      #     python manage.py collectstatic --noinput

      # - name: Migrate database
      #   env:
      #     DATABASE_URL: ${{ secrets.DB_URL }} # Set in GitHub Secrets
      #   run: |
      #     python manage.py migrate

      # - name: run test
      #   run : source ./bashScripts/run_test.sh

      - name: Notify success
        if: success()
        run: echo "Django application successfully deployed!"

  test :
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: checkout actions
        uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
        
      - name: run test
        run : source  ./bashScripts/run_test.sh
       
    

  
 