name: django-pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DB_URL: postgres://username:password@localhost/dbname

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: checkout actions
        uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --verbose
          pip install coverage

      - name: Run tests with coverage
        run: |
            coverage run manage.py test
            coverage report
            coverage html    
            
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
              name: coverage-report
              path: coverage-html/      

